apiVersion: database.digitalocean.m.crossplane.io/v1alpha1
kind: ValkeyConfig
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/valkeyconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    notifyKeyspaceEvents: KEA
    timeout: 90
    valkeyMaxmemoryPolicy: allkeys-random

---

apiVersion: database.digitalocean.m.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/valkeyconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    engine: valkey
    name: example-valkey-cluster
    nodeCount: 1
    region: nyc1
    size: db-s-1vcpu-1gb
    version: "8"
