apiVersion: spaces.digitalocean.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: spaces/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    region: nyc3
