apiVersion: spaces.digitalocean.crossplane.io/v1alpha1
kind: Cdn
metadata:
  annotations:
    meta.upbound.io/example-id: spaces/v1alpha1/cdn
  labels:
    testing.upbound.io/example-name: mycdn
  name: mycdn
spec:
  forProvider:
    bucketDomainName:
      matchLabels:
        testing.upbound.io/example-name: mybucket

---

apiVersion: spaces.digitalocean.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: spaces/v1alpha1/cdn
  labels:
    testing.upbound.io/example-name: mybucket
  name: mybucket
spec:
  forProvider:
    acl: public-read
    region: sfo2
