apiVersion: project.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/project
  labels:
    testing.upbound.io/example-name: playground
  name: playground
spec:
  forProvider:
    description: A project to represent development resources.
    environment: Development
    purpose: Web Application
