/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Alert.
func (mg *Alert) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CheckID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.CheckIDRef,
		Selector:     mg.Spec.ForProvider.CheckIDSelector,
		To: reference.To{
			List:    &CheckList{},
			Managed: &Check{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CheckID")
	}
	mg.Spec.ForProvider.CheckID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CheckIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CheckID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.CheckIDRef,
		Selector:     mg.Spec.InitProvider.CheckIDSelector,
		To: reference.To{
			List:    &CheckList{},
			Managed: &Check{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CheckID")
	}
	mg.Spec.InitProvider.CheckID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CheckIDRef = rsp.ResolvedReference

	return nil
}
