apiVersion: digitalocean.digitalocean.crossplane.io/v1alpha1
kind: Droplet
metadata:
  annotations:
    meta.upbound.io/example-id: digitalocean/v1alpha1/droplet
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    imageSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: web-1
    region: nyc2
    size: s-1vcpu-1gb
