apiVersion: digitalocean.digitalocean.crossplane.io/v1alpha1
kind: Tag
metadata:
  annotations:
    meta.upbound.io/example-id: digitalocean/v1alpha1/tag
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    name: foobar

---

apiVersion: compute.digitalocean.crossplane.io/v1alpha1
kind: Droplet
metadata:
  annotations:
    meta.upbound.io/example-id: digitalocean/v1alpha1/tag
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    imageSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: web-1
    region: nyc3
    size: s-1vcpu-1gb
    tagsRefs:
    - name: foobar
