apiVersion: networking.digitalocean.crossplane.io/v1alpha1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    dropletIdsRefs:
    - name: web
    inboundRule:
    - portRange: "22"
      protocol: tcp
      sourceAddresses:
      - 192.168.1.0/24
      - 2002:1:2::/48
    - portRange: "80"
      protocol: tcp
      sourceAddresses:
      - 0.0.0.0/0
      - ::/0
    - portRange: "443"
      protocol: tcp
      sourceAddresses:
      - 0.0.0.0/0
      - ::/0
    - protocol: icmp
      sourceAddresses:
      - 0.0.0.0/0
      - ::/0
    name: only-22-80-and-443
    outboundRule:
    - destinationAddresses:
      - 0.0.0.0/0
      - ::/0
      portRange: "53"
      protocol: tcp
    - destinationAddresses:
      - 0.0.0.0/0
      - ::/0
      portRange: "53"
      protocol: udp
    - destinationAddresses:
      - 0.0.0.0/0
      - ::/0
      protocol: icmp

---

apiVersion: droplet.digitalocean.crossplane.io/v1alpha1
kind: Droplet
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/firewall
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    imageSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: web-1
    region: nyc3
    size: s-1vcpu-1gb
