/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Cluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ConnectionPool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DB) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Firewall) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KafkaConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KafkaSchemaRegistry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KafkaTopic) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LogSinkOpenSearch) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LogSinkRsyslog) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MongoDBConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MySQLConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OpenSearchConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PostgreSQLConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RedisConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Replica) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ValkeyConfig) Hub() {}
