/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/vpc/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	ptr "k8s.io/utils/ptr"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Attachment.
func (mg *Attachment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: ptr.Deref(mg.Spec.ForProvider.ShareID, ""),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ShareIDRef,
		Selector:     mg.Spec.ForProvider.ShareIDSelector,
		To: reference.To{
			List:    &NFSShareList{},
			Managed: &NFSShare{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ShareID")
	}
	mg.Spec.ForProvider.ShareID = ptr.To(rsp.ResolvedValue)
	mg.Spec.ForProvider.ShareIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: ptr.Deref(mg.Spec.ForProvider.VPCID, ""),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.VPCIDRef,
		Selector:     mg.Spec.ForProvider.VPCIDSelector,
		To: reference.To{
			List:    &v1alpha1.VPCList{},
			Managed: &v1alpha1.VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCID")
	}
	mg.Spec.ForProvider.VPCID = ptr.To(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: ptr.Deref(mg.Spec.InitProvider.ShareID, ""),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ShareIDRef,
		Selector:     mg.Spec.InitProvider.ShareIDSelector,
		To: reference.To{
			List:    &NFSShareList{},
			Managed: &NFSShare{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ShareID")
	}
	mg.Spec.InitProvider.ShareID = ptr.To(rsp.ResolvedValue)
	mg.Spec.InitProvider.ShareIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: ptr.Deref(mg.Spec.InitProvider.VPCID, ""),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.VPCIDRef,
		Selector:     mg.Spec.InitProvider.VPCIDSelector,
		To: reference.To{
			List:    &v1alpha1.VPCList{},
			Managed: &v1alpha1.VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCID")
	}
	mg.Spec.InitProvider.VPCID = ptr.To(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this NFSShare.
func (mg *NFSShare) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: ptr.Deref(mg.Spec.ForProvider.VPCID, ""),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.VPCIDRef,
		Selector:     mg.Spec.ForProvider.VPCIDSelector,
		To: reference.To{
			List:    &v1alpha1.VPCList{},
			Managed: &v1alpha1.VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCID")
	}
	mg.Spec.ForProvider.VPCID = ptr.To(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: ptr.Deref(mg.Spec.InitProvider.VPCID, ""),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.VPCIDRef,
		Selector:     mg.Spec.InitProvider.VPCIDSelector,
		To: reference.To{
			List:    &v1alpha1.VPCList{},
			Managed: &v1alpha1.VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCID")
	}
	mg.Spec.InitProvider.VPCID = ptr.To(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Snapshot.
func (mg *Snapshot) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: ptr.Deref(mg.Spec.ForProvider.ShareID, ""),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ShareIDRef,
		Selector:     mg.Spec.ForProvider.ShareIDSelector,
		To: reference.To{
			List:    &NFSShareList{},
			Managed: &NFSShare{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ShareID")
	}
	mg.Spec.ForProvider.ShareID = ptr.To(rsp.ResolvedValue)
	mg.Spec.ForProvider.ShareIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: ptr.Deref(mg.Spec.InitProvider.ShareID, ""),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ShareIDRef,
		Selector:     mg.Spec.InitProvider.ShareIDSelector,
		To: reference.To{
			List:    &NFSShareList{},
			Managed: &NFSShare{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ShareID")
	}
	mg.Spec.InitProvider.ShareID = ptr.To(rsp.ResolvedValue)
	mg.Spec.InitProvider.ShareIDRef = rsp.ResolvedReference

	return nil
}
