apiVersion: database.digitalocean.crossplane.io/v1alpha1
kind: DB
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/db
  labels:
    testing.upbound.io/example-name: database-example
  name: database-example
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: postgres-example
    name: foobar

---

apiVersion: database.digitalocean.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/db
  labels:
    testing.upbound.io/example-name: postgres-example
  name: postgres-example
spec:
  forProvider:
    engine: pg
    name: example-postgres-cluster
    nodeCount: 1
    region: nyc1
    size: db-s-1vcpu-1gb
    version: "15"
