apiVersion: vpc.digitalocean.m.crossplane.io/v1alpha1
kind: Peering
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/peering
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    name: example-peering
    vpcIdsRefs:
    - name: vpc1
    - name: vpc2
