apiVersion: networking.digitalocean.crossplane.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/certificate
  labels:
    testing.upbound.io/example-name: cert
  name: cert
spec:
  forProvider:
    certificateChain: ${file("/Users/terraform/certs/fullchain.pem")}
    leafCertificate: ${file("/Users/terraform/certs/cert.pem")}
    name: custom-terraform-example
    privateKeySecretRef:
      key: attribute.privkey.pem
      name: example-secret
      namespace: upbound-system
    type: custom
