/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/digitalocean/v1alpha1"
	v1alpha11 "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/vpc/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Cluster.
func (mg *Cluster) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Tags),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.TagsRefs,
		Selector:      mg.Spec.ForProvider.TagsSelector,
		To: reference.To{
			List:    &v1alpha1.TagList{},
			Managed: &v1alpha1.Tag{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Tags")
	}
	mg.Spec.ForProvider.Tags = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.TagsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VPCUUIDRef,
		Selector:     mg.Spec.ForProvider.VPCUUIDSelector,
		To: reference.To{
			List:    &v1alpha11.VPCList{},
			Managed: &v1alpha11.VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCUUID")
	}
	mg.Spec.ForProvider.VPCUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCUUIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Tags),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.TagsRefs,
		Selector:      mg.Spec.InitProvider.TagsSelector,
		To: reference.To{
			List:    &v1alpha1.TagList{},
			Managed: &v1alpha1.Tag{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Tags")
	}
	mg.Spec.InitProvider.Tags = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.TagsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VPCUUIDRef,
		Selector:     mg.Spec.InitProvider.VPCUUIDSelector,
		To: reference.To{
			List:    &v1alpha11.VPCList{},
			Managed: &v1alpha11.VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCUUID")
	}
	mg.Spec.InitProvider.VPCUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCUUIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this NodePool.
func (mg *NodePool) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ClusterIDRef,
		Selector:     mg.Spec.ForProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ClusterID")
	}
	mg.Spec.ForProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ClusterIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Tags),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.TagsRefs,
		Selector:      mg.Spec.ForProvider.TagsSelector,
		To: reference.To{
			List:    &v1alpha1.TagList{},
			Managed: &v1alpha1.Tag{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Tags")
	}
	mg.Spec.ForProvider.Tags = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.TagsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ClusterID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ClusterIDRef,
		Selector:     mg.Spec.InitProvider.ClusterIDSelector,
		To: reference.To{
			List:    &ClusterList{},
			Managed: &Cluster{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ClusterID")
	}
	mg.Spec.InitProvider.ClusterID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ClusterIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Tags),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.TagsRefs,
		Selector:      mg.Spec.InitProvider.TagsSelector,
		To: reference.To{
			List:    &v1alpha1.TagList{},
			Managed: &v1alpha1.Tag{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Tags")
	}
	mg.Spec.InitProvider.Tags = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.TagsRefs = mrsp.ResolvedReferences

	return nil
}
