apiVersion: kubernetes.digitalocean.crossplane.io/v1alpha1
kind: NodePool
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/nodepool
  labels:
    testing.upbound.io/example-name: bar
  name: bar
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    labels:
      priority: high
      service: backend
    name: backend-pool
    nodeCount: 2
    size: c-2
    tags:
    - backend
    taint:
    - effect: NoSchedule
      key: workloadKind
      value: database

---

apiVersion: kubernetes.digitalocean.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/nodepool
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: foo
    nodePool:
    - name: front-end-pool
      nodeCount: 3
      size: s-2vcpu-2gb
    region: nyc1
    version: 1.22.8-do.1
