apiVersion: nfs.digitalocean.crossplane.io/v1alpha1
kind: NFSShare
metadata:
  annotations:
    meta.upbound.io/example-id: nfs/v1alpha1/nfsshare
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-nfs
    performanceTier: high
    region: nyc1
    size: 50
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: vpc.digitalocean.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: nfs/v1alpha1/nfsshare
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-vpc
    region: nyc1
