apiVersion: nfs.digitalocean.crossplane.io/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: nfs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    name: example-snapshot
    region: nyc1
    shareIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foobar

---

apiVersion: nfs.digitalocean.crossplane.io/v1alpha1
kind: NFSShare
metadata:
  annotations:
    meta.upbound.io/example-id: nfs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    name: example-nfs
    performanceTier: high
    region: nyc1
    size: 50
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foobar

---

apiVersion: vpc.digitalocean.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: nfs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    name: example-vpc
    region: nyc1
