/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type APIKeyInfosInitParameters struct {

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Updated At timestamp for the API Key
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type APIKeyInfosObservation struct {

	// API Key value
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Deleted At timestamp for the API Key
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Updated At timestamp for the API Key
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type APIKeyInfosParameters struct {

	// Created By user ID for the API Key
	// +kubebuilder:validation:Optional
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Updated At timestamp for the API Key
	// +kubebuilder:validation:Optional
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type APIKeysInitParameters struct {

	// API Key value
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`
}

type APIKeysObservation struct {

	// API Key value
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`
}

type APIKeysParameters struct {

	// API Key value
	// +kubebuilder:validation:Optional
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`
}

type AgentDeploymentInitParameters struct {

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Status of the Deployment
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Url of the Deployment
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// argument must be set inside this block. Valid values for visibility are: VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_PLAYGROUND, VISIBILITY_DISABLED, or VISIBILITY_UNKNOWN.
	// Visibility of the Deployment
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type AgentDeploymentObservation struct {

	// API Key value
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Status of the Deployment
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Url of the Deployment
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the Agent
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// argument must be set inside this block. Valid values for visibility are: VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_PLAYGROUND, VISIBILITY_DISABLED, or VISIBILITY_UNKNOWN.
	// Visibility of the Deployment
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type AgentDeploymentParameters struct {

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Status of the Deployment
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Url of the Deployment
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// argument must be set inside this block. Valid values for visibility are: VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_PLAYGROUND, VISIBILITY_DISABLED, or VISIBILITY_UNKNOWN.
	// Visibility of the Deployment
	// +kubebuilder:validation:Optional
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type AgentGuardrailInitParameters struct {

	// ).
	// Agent UUID for the Guardrail
	AgentUUID *string `json:"agentUuid,omitempty" tf:"agent_uuid,omitempty"`

	// Default response for the Guardrail
	DefaultResponse *string `json:"defaultResponse,omitempty" tf:"default_response,omitempty"`

	// Description of the Guardrail
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ).
	// Guardrail UUID
	GuardrailUUID *string `json:"guardrailUuid,omitempty" tf:"guardrail_uuid,omitempty"`

	// Indicates if the Guardrail is default
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// Name of Guardrail
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Priority of the Guardrail
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// Type of the Guardrail
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// ).
	// Guardrail UUID
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AgentGuardrailObservation struct {

	// ).
	// Agent UUID for the Guardrail
	AgentUUID *string `json:"agentUuid,omitempty" tf:"agent_uuid,omitempty"`

	// Created At timestamp for the Guardrail
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Default response for the Guardrail
	DefaultResponse *string `json:"defaultResponse,omitempty" tf:"default_response,omitempty"`

	// Description of the Guardrail
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ).
	// Guardrail UUID
	GuardrailUUID *string `json:"guardrailUuid,omitempty" tf:"guardrail_uuid,omitempty"`

	// Indicates if the Guardrail is attached
	IsAttached *bool `json:"isAttached,omitempty" tf:"is_attached,omitempty"`

	// Indicates if the Guardrail is default
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// Name of Guardrail
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Priority of the Guardrail
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// Type of the Guardrail
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// ).
	// Guardrail UUID
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the Guardrail
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type AgentGuardrailParameters struct {

	// ).
	// Agent UUID for the Guardrail
	// +kubebuilder:validation:Optional
	AgentUUID *string `json:"agentUuid,omitempty" tf:"agent_uuid,omitempty"`

	// Default response for the Guardrail
	// +kubebuilder:validation:Optional
	DefaultResponse *string `json:"defaultResponse,omitempty" tf:"default_response,omitempty"`

	// Description of the Guardrail
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ).
	// Guardrail UUID
	// +kubebuilder:validation:Optional
	GuardrailUUID *string `json:"guardrailUuid,omitempty" tf:"guardrail_uuid,omitempty"`

	// Indicates if the Guardrail is default
	// +kubebuilder:validation:Optional
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// Name of Guardrail
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Priority of the Guardrail
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// Type of the Guardrail
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// ).
	// Guardrail UUID
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AgentInitParameters struct {

	// List of API Key Infos
	APIKeyInfos []APIKeyInfosInitParameters `json:"apiKeyInfos,omitempty" tf:"api_key_infos,omitempty"`

	// List of API Keys
	APIKeys []APIKeysInitParameters `json:"apiKeys,omitempty" tf:"api_keys,omitempty"`

	// AgentGuardrail represents a Guardrail attached to Gen AI Agent
	AgentGuardrail []AgentGuardrailInitParameters `json:"agentGuardrail,omitempty" tf:"agent_guardrail,omitempty"`

	// Anthropic API Key information
	AnthropicAPIKey []AnthropicAPIKeyInitParameters `json:"anthropicApiKey,omitempty" tf:"anthropic_api_key,omitempty"`

	// ).
	// Optional Anthropic API key ID to use with Anthropic models
	AnthropicKeyUUID *string `json:"anthropicKeyUuid,omitempty" tf:"anthropic_key_uuid,omitempty"`

	// ChatBot configuration
	Chatbot []ChatbotInitParameters `json:"chatbot,omitempty" tf:"chatbot,omitempty"`

	// List of Chatbot Identifiers
	ChatbotIdentifiers []ChatbotIdentifiersInitParameters `json:"chatbotIdentifiers,omitempty" tf:"chatbot_identifiers,omitempty"`

	// List of child agents
	ChildAgents []ChildAgentsInitParameters `json:"childAgents,omitempty" tf:"child_agents,omitempty"`

	// Timestamp when the Agent was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// List of API Key Infos
	Deployment []AgentDeploymentInitParameters `json:"deployment,omitempty" tf:"deployment,omitempty"`

	// Description for the Agent
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// List of Functions
	Functions []FunctionsInitParameters `json:"functions,omitempty" tf:"functions,omitempty"`

	// If case condition
	IfCase *string `json:"ifCase,omitempty" tf:"if_case,omitempty"`

	// Instruction for the Agent
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// K value
	K *float64 `json:"k,omitempty" tf:"k,omitempty"`

	// ).
	// Ids of the knowledge base(s) to attach to the agent
	KnowledgeBaseUUID []*string `json:"knowledgeBaseUuid,omitempty" tf:"knowledge_base_uuid,omitempty"`

	// List of Knowledge Bases
	KnowledgeBases []KnowledgeBasesInitParameters `json:"knowledgeBases,omitempty" tf:"knowledge_bases,omitempty"`

	// Maximum tokens allowed
	MaxTokens *float64 `json:"maxTokens,omitempty" tf:"max_tokens,omitempty"`

	// Model of the Agent
	Model []ModelInitParameters `json:"model,omitempty" tf:"model,omitempty"`

	// ).
	// Model UUID of the Agent
	ModelUUID *string `json:"modelUuid,omitempty" tf:"model_uuid,omitempty"`

	// Name of the Agent
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// OpenAI API Key information
	OpenAIAPIKey []OpenAIAPIKeyInitParameters `json:"openAiApiKey,omitempty" tf:"open_ai_api_key,omitempty"`

	// ).
	// Optional OpenAI API key ID to use with OpenAI models
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/gradientai/v1alpha1.OpenAIAPIKey
	OpenAIKeyUUID *string `json:"openAiKeyUuid,omitempty" tf:"open_ai_key_uuid,omitempty"`

	// Reference to a OpenAIAPIKey in gradientai to populate openAiKeyUuid.
	// +kubebuilder:validation:Optional
	OpenAIKeyUUIDRef *v1.Reference `json:"openAiKeyUuidRef,omitempty" tf:"-"`

	// Selector for a OpenAIAPIKey in gradientai to populate openAiKeyUuid.
	// +kubebuilder:validation:Optional
	OpenAIKeyUUIDSelector *v1.Selector `json:"openAiKeyUuidSelector,omitempty" tf:"-"`

	// List of child agents
	ParentAgents []ParentAgentsInitParameters `json:"parentAgents,omitempty" tf:"parent_agents,omitempty"`

	// Project ID of the Agent
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Indicates if the agent should provide citations in responses
	ProvideCitations *bool `json:"provideCitations,omitempty" tf:"provide_citations,omitempty"`

	// Region where the Agent is deployed
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Retrieval method used
	RetrievalMethod *string `json:"retrievalMethod,omitempty" tf:"retrieval_method,omitempty"`

	// User who created the route
	RouteCreatedBy *string `json:"routeCreatedBy,omitempty" tf:"route_created_by,omitempty"`

	// Route name
	RouteName *string `json:"routeName,omitempty" tf:"route_name,omitempty"`

	// ).
	// Route UUID
	RouteUUID *string `json:"routeUuid,omitempty" tf:"route_uuid,omitempty"`

	// List of Tags
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Agent temperature setting
	Temperature *float64 `json:"temperature,omitempty" tf:"temperature,omitempty"`

	// Agent Template
	Template []TemplateInitParameters `json:"template,omitempty" tf:"template,omitempty"`

	// Top P sampling parameter
	TopP *float64 `json:"topP,omitempty" tf:"top_p,omitempty"`

	// URL for the Agent
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// User ID linked with the Agent
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type AgentObservation struct {

	// List of API Key Infos
	APIKeyInfos []APIKeyInfosObservation `json:"apiKeyInfos,omitempty" tf:"api_key_infos,omitempty"`

	// List of API Keys
	APIKeys []APIKeysObservation `json:"apiKeys,omitempty" tf:"api_keys,omitempty"`

	// AgentGuardrail represents a Guardrail attached to Gen AI Agent
	AgentGuardrail []AgentGuardrailObservation `json:"agentGuardrail,omitempty" tf:"agent_guardrail,omitempty"`

	// Anthropic API Key information
	AnthropicAPIKey []AnthropicAPIKeyObservation `json:"anthropicApiKey,omitempty" tf:"anthropic_api_key,omitempty"`

	// ).
	// Optional Anthropic API key ID to use with Anthropic models
	AnthropicKeyUUID *string `json:"anthropicKeyUuid,omitempty" tf:"anthropic_key_uuid,omitempty"`

	// ChatBot configuration
	Chatbot []ChatbotObservation `json:"chatbot,omitempty" tf:"chatbot,omitempty"`

	// List of Chatbot Identifiers
	ChatbotIdentifiers []ChatbotIdentifiersObservation `json:"chatbotIdentifiers,omitempty" tf:"chatbot_identifiers,omitempty"`

	// List of child agents
	ChildAgents []ChildAgentsObservation `json:"childAgents,omitempty" tf:"child_agents,omitempty"`

	// Timestamp when the Agent was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// List of API Key Infos
	Deployment []AgentDeploymentObservation `json:"deployment,omitempty" tf:"deployment,omitempty"`

	// Description for the Agent
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// List of Functions
	Functions []FunctionsObservation `json:"functions,omitempty" tf:"functions,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If case condition
	IfCase *string `json:"ifCase,omitempty" tf:"if_case,omitempty"`

	// Instruction for the Agent
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// K value
	K *float64 `json:"k,omitempty" tf:"k,omitempty"`

	// ).
	// Ids of the knowledge base(s) to attach to the agent
	KnowledgeBaseUUID []*string `json:"knowledgeBaseUuid,omitempty" tf:"knowledge_base_uuid,omitempty"`

	// List of Knowledge Bases
	KnowledgeBases []KnowledgeBasesObservation `json:"knowledgeBases,omitempty" tf:"knowledge_bases,omitempty"`

	// Maximum tokens allowed
	MaxTokens *float64 `json:"maxTokens,omitempty" tf:"max_tokens,omitempty"`

	// Model of the Agent
	Model []ModelObservation `json:"model,omitempty" tf:"model,omitempty"`

	// ).
	// Model UUID of the Agent
	ModelUUID *string `json:"modelUuid,omitempty" tf:"model_uuid,omitempty"`

	// Name of the Agent
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// OpenAI API Key information
	OpenAIAPIKey []OpenAIAPIKeyObservation `json:"openAiApiKey,omitempty" tf:"open_ai_api_key,omitempty"`

	// ).
	// Optional OpenAI API key ID to use with OpenAI models
	OpenAIKeyUUID *string `json:"openAiKeyUuid,omitempty" tf:"open_ai_key_uuid,omitempty"`

	// List of child agents
	ParentAgents []ParentAgentsObservation `json:"parentAgents,omitempty" tf:"parent_agents,omitempty"`

	// Project ID of the Agent
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Indicates if the agent should provide citations in responses
	ProvideCitations *bool `json:"provideCitations,omitempty" tf:"provide_citations,omitempty"`

	// Region where the Agent is deployed
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Retrieval method used
	RetrievalMethod *string `json:"retrievalMethod,omitempty" tf:"retrieval_method,omitempty"`

	// Timestamp when the route was created
	RouteCreatedAt *string `json:"routeCreatedAt,omitempty" tf:"route_created_at,omitempty"`

	// User who created the route
	RouteCreatedBy *string `json:"routeCreatedBy,omitempty" tf:"route_created_by,omitempty"`

	// Route name
	RouteName *string `json:"routeName,omitempty" tf:"route_name,omitempty"`

	// ).
	// Route UUID
	RouteUUID *string `json:"routeUuid,omitempty" tf:"route_uuid,omitempty"`

	// List of Tags
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Agent temperature setting
	Temperature *float64 `json:"temperature,omitempty" tf:"temperature,omitempty"`

	// Agent Template
	Template []TemplateObservation `json:"template,omitempty" tf:"template,omitempty"`

	// Top P sampling parameter
	TopP *float64 `json:"topP,omitempty" tf:"top_p,omitempty"`

	// URL for the Agent
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Timestamp when the Agent was updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// User ID linked with the Agent
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type AgentParameters struct {

	// List of API Key Infos
	// +kubebuilder:validation:Optional
	APIKeyInfos []APIKeyInfosParameters `json:"apiKeyInfos,omitempty" tf:"api_key_infos,omitempty"`

	// List of API Keys
	// +kubebuilder:validation:Optional
	APIKeys []APIKeysParameters `json:"apiKeys,omitempty" tf:"api_keys,omitempty"`

	// AgentGuardrail represents a Guardrail attached to Gen AI Agent
	// +kubebuilder:validation:Optional
	AgentGuardrail []AgentGuardrailParameters `json:"agentGuardrail,omitempty" tf:"agent_guardrail,omitempty"`

	// Anthropic API Key information
	// +kubebuilder:validation:Optional
	AnthropicAPIKey []AnthropicAPIKeyParameters `json:"anthropicApiKey,omitempty" tf:"anthropic_api_key,omitempty"`

	// ).
	// Optional Anthropic API key ID to use with Anthropic models
	// +kubebuilder:validation:Optional
	AnthropicKeyUUID *string `json:"anthropicKeyUuid,omitempty" tf:"anthropic_key_uuid,omitempty"`

	// ChatBot configuration
	// +kubebuilder:validation:Optional
	Chatbot []ChatbotParameters `json:"chatbot,omitempty" tf:"chatbot,omitempty"`

	// List of Chatbot Identifiers
	// +kubebuilder:validation:Optional
	ChatbotIdentifiers []ChatbotIdentifiersParameters `json:"chatbotIdentifiers,omitempty" tf:"chatbot_identifiers,omitempty"`

	// List of child agents
	// +kubebuilder:validation:Optional
	ChildAgents []ChildAgentsParameters `json:"childAgents,omitempty" tf:"child_agents,omitempty"`

	// Timestamp when the Agent was created
	// +kubebuilder:validation:Optional
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// List of API Key Infos
	// +kubebuilder:validation:Optional
	Deployment []AgentDeploymentParameters `json:"deployment,omitempty" tf:"deployment,omitempty"`

	// Description for the Agent
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// List of Functions
	// +kubebuilder:validation:Optional
	Functions []FunctionsParameters `json:"functions,omitempty" tf:"functions,omitempty"`

	// If case condition
	// +kubebuilder:validation:Optional
	IfCase *string `json:"ifCase,omitempty" tf:"if_case,omitempty"`

	// Instruction for the Agent
	// +kubebuilder:validation:Optional
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// K value
	// +kubebuilder:validation:Optional
	K *float64 `json:"k,omitempty" tf:"k,omitempty"`

	// ).
	// Ids of the knowledge base(s) to attach to the agent
	// +kubebuilder:validation:Optional
	KnowledgeBaseUUID []*string `json:"knowledgeBaseUuid,omitempty" tf:"knowledge_base_uuid,omitempty"`

	// List of Knowledge Bases
	// +kubebuilder:validation:Optional
	KnowledgeBases []KnowledgeBasesParameters `json:"knowledgeBases,omitempty" tf:"knowledge_bases,omitempty"`

	// Maximum tokens allowed
	// +kubebuilder:validation:Optional
	MaxTokens *float64 `json:"maxTokens,omitempty" tf:"max_tokens,omitempty"`

	// Model of the Agent
	// +kubebuilder:validation:Optional
	Model []ModelParameters `json:"model,omitempty" tf:"model,omitempty"`

	// ).
	// Model UUID of the Agent
	// +kubebuilder:validation:Optional
	ModelUUID *string `json:"modelUuid,omitempty" tf:"model_uuid,omitempty"`

	// Name of the Agent
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// OpenAI API Key information
	// +kubebuilder:validation:Optional
	OpenAIAPIKey []OpenAIAPIKeyParameters `json:"openAiApiKey,omitempty" tf:"open_ai_api_key,omitempty"`

	// ).
	// Optional OpenAI API key ID to use with OpenAI models
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/gradientai/v1alpha1.OpenAIAPIKey
	// +kubebuilder:validation:Optional
	OpenAIKeyUUID *string `json:"openAiKeyUuid,omitempty" tf:"open_ai_key_uuid,omitempty"`

	// Reference to a OpenAIAPIKey in gradientai to populate openAiKeyUuid.
	// +kubebuilder:validation:Optional
	OpenAIKeyUUIDRef *v1.Reference `json:"openAiKeyUuidRef,omitempty" tf:"-"`

	// Selector for a OpenAIAPIKey in gradientai to populate openAiKeyUuid.
	// +kubebuilder:validation:Optional
	OpenAIKeyUUIDSelector *v1.Selector `json:"openAiKeyUuidSelector,omitempty" tf:"-"`

	// List of child agents
	// +kubebuilder:validation:Optional
	ParentAgents []ParentAgentsParameters `json:"parentAgents,omitempty" tf:"parent_agents,omitempty"`

	// Project ID of the Agent
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// Indicates if the agent should provide citations in responses
	// +kubebuilder:validation:Optional
	ProvideCitations *bool `json:"provideCitations,omitempty" tf:"provide_citations,omitempty"`

	// Region where the Agent is deployed
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Retrieval method used
	// +kubebuilder:validation:Optional
	RetrievalMethod *string `json:"retrievalMethod,omitempty" tf:"retrieval_method,omitempty"`

	// User who created the route
	// +kubebuilder:validation:Optional
	RouteCreatedBy *string `json:"routeCreatedBy,omitempty" tf:"route_created_by,omitempty"`

	// Route name
	// +kubebuilder:validation:Optional
	RouteName *string `json:"routeName,omitempty" tf:"route_name,omitempty"`

	// ).
	// Route UUID
	// +kubebuilder:validation:Optional
	RouteUUID *string `json:"routeUuid,omitempty" tf:"route_uuid,omitempty"`

	// List of Tags
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Agent temperature setting
	// +kubebuilder:validation:Optional
	Temperature *float64 `json:"temperature,omitempty" tf:"temperature,omitempty"`

	// Agent Template
	// +kubebuilder:validation:Optional
	Template []TemplateParameters `json:"template,omitempty" tf:"template,omitempty"`

	// Top P sampling parameter
	// +kubebuilder:validation:Optional
	TopP *float64 `json:"topP,omitempty" tf:"top_p,omitempty"`

	// URL for the Agent
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// User ID linked with the Agent
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type AgreementInitParameters struct {

	// Description of the agreement
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the agreement
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// URL of the agreement
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// UUID of the agreement
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AgreementObservation struct {

	// Description of the agreement
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the agreement
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// URL of the agreement
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// UUID of the agreement
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AgreementParameters struct {

	// Description of the agreement
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the agreement
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// URL of the agreement
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// UUID of the agreement
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AnthropicAPIKeyInitParameters struct {

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type AnthropicAPIKeyObservation struct {

	// Timestamp when the API Key was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Deleted At timestamp for the API Key
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the API Key
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type AnthropicAPIKeyParameters struct {

	// Created By user ID for the API Key
	// +kubebuilder:validation:Optional
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ChatbotIdentifiersInitParameters struct {
}

type ChatbotIdentifiersObservation struct {
	ChatbotID *string `json:"chatbotId,omitempty" tf:"chatbot_id,omitempty"`
}

type ChatbotIdentifiersParameters struct {
}

type ChatbotInitParameters struct {

	// Background color for the chatbot button
	ButtonBackgroundColor *string `json:"buttonBackgroundColor,omitempty" tf:"button_background_color,omitempty"`

	// Logo for the chatbot
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Name of the chatbot
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Primary color for the chatbot
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// Secondary color for the chatbot
	SecondaryColor *string `json:"secondaryColor,omitempty" tf:"secondary_color,omitempty"`

	// Starting message for the chatbot
	StartingMessage *string `json:"startingMessage,omitempty" tf:"starting_message,omitempty"`
}

type ChatbotObservation struct {

	// Background color for the chatbot button
	ButtonBackgroundColor *string `json:"buttonBackgroundColor,omitempty" tf:"button_background_color,omitempty"`

	// Logo for the chatbot
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Name of the chatbot
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Primary color for the chatbot
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// Secondary color for the chatbot
	SecondaryColor *string `json:"secondaryColor,omitempty" tf:"secondary_color,omitempty"`

	// Starting message for the chatbot
	StartingMessage *string `json:"startingMessage,omitempty" tf:"starting_message,omitempty"`
}

type ChatbotParameters struct {

	// Background color for the chatbot button
	// +kubebuilder:validation:Optional
	ButtonBackgroundColor *string `json:"buttonBackgroundColor,omitempty" tf:"button_background_color,omitempty"`

	// Logo for the chatbot
	// +kubebuilder:validation:Optional
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Name of the chatbot
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Primary color for the chatbot
	// +kubebuilder:validation:Optional
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// Secondary color for the chatbot
	// +kubebuilder:validation:Optional
	SecondaryColor *string `json:"secondaryColor,omitempty" tf:"secondary_color,omitempty"`

	// Starting message for the chatbot
	// +kubebuilder:validation:Optional
	StartingMessage *string `json:"startingMessage,omitempty" tf:"starting_message,omitempty"`
}

type ChildAgentsAPIKeyInfosInitParameters struct {

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Updated At timestamp for the API Key
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ChildAgentsAPIKeyInfosObservation struct {

	// API Key value
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Deleted At timestamp for the API Key
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Updated At timestamp for the API Key
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ChildAgentsAPIKeyInfosParameters struct {

	// Created By user ID for the API Key
	// +kubebuilder:validation:Optional
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Updated At timestamp for the API Key
	// +kubebuilder:validation:Optional
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ChildAgentsAPIKeysInitParameters struct {

	// API Key value
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`
}

type ChildAgentsAPIKeysObservation struct {

	// API Key value
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`
}

type ChildAgentsAPIKeysParameters struct {

	// API Key value
	// +kubebuilder:validation:Optional
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`
}

type ChildAgentsAnthropicAPIKeyInitParameters struct {

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ChildAgentsAnthropicAPIKeyObservation struct {

	// Timestamp when the API Key was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Deleted At timestamp for the API Key
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the API Key
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type ChildAgentsAnthropicAPIKeyParameters struct {

	// Created By user ID for the API Key
	// +kubebuilder:validation:Optional
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ChildAgentsChatbotIdentifiersInitParameters struct {
}

type ChildAgentsChatbotIdentifiersObservation struct {
	ChatbotID *string `json:"chatbotId,omitempty" tf:"chatbot_id,omitempty"`
}

type ChildAgentsChatbotIdentifiersParameters struct {
}

type ChildAgentsChatbotInitParameters struct {

	// Background color for the chatbot button
	ButtonBackgroundColor *string `json:"buttonBackgroundColor,omitempty" tf:"button_background_color,omitempty"`

	// Logo for the chatbot
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Name of the chatbot
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Primary color for the chatbot
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// Secondary color for the chatbot
	SecondaryColor *string `json:"secondaryColor,omitempty" tf:"secondary_color,omitempty"`

	// Starting message for the chatbot
	StartingMessage *string `json:"startingMessage,omitempty" tf:"starting_message,omitempty"`
}

type ChildAgentsChatbotObservation struct {

	// Background color for the chatbot button
	ButtonBackgroundColor *string `json:"buttonBackgroundColor,omitempty" tf:"button_background_color,omitempty"`

	// Logo for the chatbot
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Name of the chatbot
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Primary color for the chatbot
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// Secondary color for the chatbot
	SecondaryColor *string `json:"secondaryColor,omitempty" tf:"secondary_color,omitempty"`

	// Starting message for the chatbot
	StartingMessage *string `json:"startingMessage,omitempty" tf:"starting_message,omitempty"`
}

type ChildAgentsChatbotParameters struct {

	// Background color for the chatbot button
	// +kubebuilder:validation:Optional
	ButtonBackgroundColor *string `json:"buttonBackgroundColor,omitempty" tf:"button_background_color,omitempty"`

	// Logo for the chatbot
	// +kubebuilder:validation:Optional
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Name of the chatbot
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Primary color for the chatbot
	// +kubebuilder:validation:Optional
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// Secondary color for the chatbot
	// +kubebuilder:validation:Optional
	SecondaryColor *string `json:"secondaryColor,omitempty" tf:"secondary_color,omitempty"`

	// Starting message for the chatbot
	// +kubebuilder:validation:Optional
	StartingMessage *string `json:"startingMessage,omitempty" tf:"starting_message,omitempty"`
}

type ChildAgentsInitParameters struct {

	// List of API Key Infos
	APIKeyInfos []ChildAgentsAPIKeyInfosInitParameters `json:"apiKeyInfos,omitempty" tf:"api_key_infos,omitempty"`

	// List of API Keys
	APIKeys []ChildAgentsAPIKeysInitParameters `json:"apiKeys,omitempty" tf:"api_keys,omitempty"`

	// Anthropic API Key information
	AnthropicAPIKey []ChildAgentsAnthropicAPIKeyInitParameters `json:"anthropicApiKey,omitempty" tf:"anthropic_api_key,omitempty"`

	// ChatBot configuration
	Chatbot []ChildAgentsChatbotInitParameters `json:"chatbot,omitempty" tf:"chatbot,omitempty"`

	// List of Chatbot Identifiers
	ChatbotIdentifiers []ChildAgentsChatbotIdentifiersInitParameters `json:"chatbotIdentifiers,omitempty" tf:"chatbot_identifiers,omitempty"`

	// List of API Key Infos
	Deployment []DeploymentInitParameters `json:"deployment,omitempty" tf:"deployment,omitempty"`

	// Description for the Agent
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Instruction for the Agent
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// ).
	// Model UUID of the Agent
	ModelUUID *string `json:"modelUuid,omitempty" tf:"model_uuid,omitempty"`

	// Name of the Agent
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Agent
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region where the Agent is deployed
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ChildAgentsObservation struct {

	// List of API Key Infos
	APIKeyInfos []ChildAgentsAPIKeyInfosObservation `json:"apiKeyInfos,omitempty" tf:"api_key_infos,omitempty"`

	// List of API Keys
	APIKeys []ChildAgentsAPIKeysObservation `json:"apiKeys,omitempty" tf:"api_keys,omitempty"`

	// ID of the child agent
	AgentID *string `json:"agentId,omitempty" tf:"agent_id,omitempty"`

	// Anthropic API Key information
	AnthropicAPIKey []ChildAgentsAnthropicAPIKeyObservation `json:"anthropicApiKey,omitempty" tf:"anthropic_api_key,omitempty"`

	// ChatBot configuration
	Chatbot []ChildAgentsChatbotObservation `json:"chatbot,omitempty" tf:"chatbot,omitempty"`

	// List of Chatbot Identifiers
	ChatbotIdentifiers []ChildAgentsChatbotIdentifiersObservation `json:"chatbotIdentifiers,omitempty" tf:"chatbot_identifiers,omitempty"`

	// List of API Key Infos
	Deployment []DeploymentObservation `json:"deployment,omitempty" tf:"deployment,omitempty"`

	// Description for the Agent
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Instruction for the Agent
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// ).
	// Model UUID of the Agent
	ModelUUID *string `json:"modelUuid,omitempty" tf:"model_uuid,omitempty"`

	// Name of the Agent
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Agent
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region where the Agent is deployed
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ChildAgentsParameters struct {

	// List of API Key Infos
	// +kubebuilder:validation:Optional
	APIKeyInfos []ChildAgentsAPIKeyInfosParameters `json:"apiKeyInfos,omitempty" tf:"api_key_infos,omitempty"`

	// List of API Keys
	// +kubebuilder:validation:Optional
	APIKeys []ChildAgentsAPIKeysParameters `json:"apiKeys,omitempty" tf:"api_keys,omitempty"`

	// Anthropic API Key information
	// +kubebuilder:validation:Optional
	AnthropicAPIKey []ChildAgentsAnthropicAPIKeyParameters `json:"anthropicApiKey,omitempty" tf:"anthropic_api_key,omitempty"`

	// ChatBot configuration
	// +kubebuilder:validation:Optional
	Chatbot []ChildAgentsChatbotParameters `json:"chatbot,omitempty" tf:"chatbot,omitempty"`

	// List of Chatbot Identifiers
	// +kubebuilder:validation:Optional
	ChatbotIdentifiers []ChildAgentsChatbotIdentifiersParameters `json:"chatbotIdentifiers,omitempty" tf:"chatbot_identifiers,omitempty"`

	// List of API Key Infos
	// +kubebuilder:validation:Optional
	Deployment []DeploymentParameters `json:"deployment,omitempty" tf:"deployment,omitempty"`

	// Description for the Agent
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Instruction for the Agent
	// +kubebuilder:validation:Optional
	Instruction *string `json:"instruction" tf:"instruction,omitempty"`

	// ).
	// Model UUID of the Agent
	// +kubebuilder:validation:Optional
	ModelUUID *string `json:"modelUuid" tf:"model_uuid,omitempty"`

	// Name of the Agent
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Project ID of the Agent
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId" tf:"project_id,omitempty"`

	// Region where the Agent is deployed
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`
}

type DeploymentInitParameters struct {

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Status of the Deployment
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Url of the Deployment
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// argument must be set inside this block. Valid values for visibility are: VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_PLAYGROUND, VISIBILITY_DISABLED, or VISIBILITY_UNKNOWN.
	// Visibility of the Deployment
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type DeploymentObservation struct {

	// API Key value
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Status of the Deployment
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Url of the Deployment
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the Agent
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// argument must be set inside this block. Valid values for visibility are: VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_PLAYGROUND, VISIBILITY_DISABLED, or VISIBILITY_UNKNOWN.
	// Visibility of the Deployment
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type DeploymentParameters struct {

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Status of the Deployment
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Url of the Deployment
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// argument must be set inside this block. Valid values for visibility are: VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_PLAYGROUND, VISIBILITY_DISABLED, or VISIBILITY_UNKNOWN.
	// Visibility of the Deployment
	// +kubebuilder:validation:Optional
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type FunctionsInitParameters struct {

	// API Key value
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// Description of the Function
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of function
	Faasname *string `json:"faasname,omitempty" tf:"faasname,omitempty"`

	// Namespace of function
	Faasnamespace *string `json:"faasnamespace,omitempty" tf:"faasnamespace,omitempty"`

	// ).
	// Guardrail UUID for the Function
	GuardrailUUID *string `json:"guardrailUuid,omitempty" tf:"guardrail_uuid,omitempty"`

	// Name of function
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Url of the Deployment
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type FunctionsObservation struct {

	// API Key value
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// Created At timestamp for the Function
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Description of the Function
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of function
	Faasname *string `json:"faasname,omitempty" tf:"faasname,omitempty"`

	// Namespace of function
	Faasnamespace *string `json:"faasnamespace,omitempty" tf:"faasnamespace,omitempty"`

	// ).
	// Guardrail UUID for the Function
	GuardrailUUID *string `json:"guardrailUuid,omitempty" tf:"guardrail_uuid,omitempty"`

	// Name of function
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Url of the Deployment
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the Agent
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type FunctionsParameters struct {

	// API Key value
	// +kubebuilder:validation:Optional
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// Description of the Function
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of function
	// +kubebuilder:validation:Optional
	Faasname *string `json:"faasname,omitempty" tf:"faasname,omitempty"`

	// Namespace of function
	// +kubebuilder:validation:Optional
	Faasnamespace *string `json:"faasnamespace,omitempty" tf:"faasnamespace,omitempty"`

	// ).
	// Guardrail UUID for the Function
	// +kubebuilder:validation:Optional
	GuardrailUUID *string `json:"guardrailUuid,omitempty" tf:"guardrail_uuid,omitempty"`

	// Name of function
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Url of the Deployment
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type KnowledgeBasesInitParameters struct {

	// Database ID of the Knowledge Base
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// ).
	// Embedding model UUID for the Knowledge Base
	EmbeddingModelUUID *string `json:"embeddingModelUuid,omitempty" tf:"embedding_model_uuid,omitempty"`

	// Indicates if the Knowledge Base is public
	IsPublic *bool `json:"isPublic,omitempty" tf:"is_public,omitempty"`

	// Last indexing job for the Knowledge Base
	LastIndexingJob []LastIndexingJobInitParameters `json:"lastIndexingJob,omitempty" tf:"last_indexing_job,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Knowledge Base
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region of the Knowledge Base
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// List of tags
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User ID of the Knowledge Base
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type KnowledgeBasesLastIndexingJobInitParameters struct {

	// Number of completed datasources in the last indexing job
	CompletedDatasources *float64 `json:"completedDatasources,omitempty" tf:"completed_datasources,omitempty"`

	// Datasource UUIDs for the last indexing job
	DataSourceUuids []*string `json:"dataSourceUuids,omitempty" tf:"data_source_uuids,omitempty"`

	// Phase of the last indexing job
	Phase *string `json:"phase,omitempty" tf:"phase,omitempty"`

	// Number of tokens processed in the last indexing job
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`

	// Total number of datasources in the last indexing job
	TotalDatasources *float64 `json:"totalDatasources,omitempty" tf:"total_datasources,omitempty"`

	// ).
	// UUID  of the last indexing job
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type KnowledgeBasesLastIndexingJobObservation struct {

	// Number of completed datasources in the last indexing job
	CompletedDatasources *float64 `json:"completedDatasources,omitempty" tf:"completed_datasources,omitempty"`

	// Created At timestamp for the last indexing job
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Datasource UUIDs for the last indexing job
	DataSourceUuids []*string `json:"dataSourceUuids,omitempty" tf:"data_source_uuids,omitempty"`

	// Timestamp when the last indexing job finished
	FinishedAt *string `json:"finishedAt,omitempty" tf:"finished_at,omitempty"`

	// ).
	// UUID  of the Knowledge Base for the last indexing job
	KnowledgeBaseUUID *string `json:"knowledgeBaseUuid,omitempty" tf:"knowledge_base_uuid,omitempty"`

	// Phase of the last indexing job
	Phase *string `json:"phase,omitempty" tf:"phase,omitempty"`

	// Timestamp when the last indexing job started
	StartedAt *string `json:"startedAt,omitempty" tf:"started_at,omitempty"`

	// Number of tokens processed in the last indexing job
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`

	// Total number of datasources in the last indexing job
	TotalDatasources *float64 `json:"totalDatasources,omitempty" tf:"total_datasources,omitempty"`

	// ).
	// UUID  of the last indexing job
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Timestamp when the last indexing job updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type KnowledgeBasesLastIndexingJobParameters struct {

	// Number of completed datasources in the last indexing job
	// +kubebuilder:validation:Optional
	CompletedDatasources *float64 `json:"completedDatasources,omitempty" tf:"completed_datasources,omitempty"`

	// Datasource UUIDs for the last indexing job
	// +kubebuilder:validation:Optional
	DataSourceUuids []*string `json:"dataSourceUuids,omitempty" tf:"data_source_uuids,omitempty"`

	// Phase of the last indexing job
	// +kubebuilder:validation:Optional
	Phase *string `json:"phase,omitempty" tf:"phase,omitempty"`

	// Number of tokens processed in the last indexing job
	// +kubebuilder:validation:Optional
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`

	// Total number of datasources in the last indexing job
	// +kubebuilder:validation:Optional
	TotalDatasources *float64 `json:"totalDatasources,omitempty" tf:"total_datasources,omitempty"`

	// ).
	// UUID  of the last indexing job
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type KnowledgeBasesObservation struct {

	// Timestamp when the Knowledge Base was added to the Agent
	AddedToAgentAt *string `json:"addedToAgentAt,omitempty" tf:"added_to_agent_at,omitempty"`

	// Created At timestamp for the Knowledge Base
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Database ID of the Knowledge Base
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// ).
	// Embedding model UUID for the Knowledge Base
	EmbeddingModelUUID *string `json:"embeddingModelUuid,omitempty" tf:"embedding_model_uuid,omitempty"`

	// Indicates if the Knowledge Base is public
	IsPublic *bool `json:"isPublic,omitempty" tf:"is_public,omitempty"`

	// Last indexing job for the Knowledge Base
	LastIndexingJob []LastIndexingJobObservation `json:"lastIndexingJob,omitempty" tf:"last_indexing_job,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Knowledge Base
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region of the Knowledge Base
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// List of tags
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// ).
	// UUID of the Knowledge Base
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Timestamp when the Knowledge Base was updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// User ID of the Knowledge Base
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type KnowledgeBasesParameters struct {

	// Database ID of the Knowledge Base
	// +kubebuilder:validation:Optional
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// ).
	// Embedding model UUID for the Knowledge Base
	// +kubebuilder:validation:Optional
	EmbeddingModelUUID *string `json:"embeddingModelUuid,omitempty" tf:"embedding_model_uuid,omitempty"`

	// Indicates if the Knowledge Base is public
	// +kubebuilder:validation:Optional
	IsPublic *bool `json:"isPublic,omitempty" tf:"is_public,omitempty"`

	// Last indexing job for the Knowledge Base
	// +kubebuilder:validation:Optional
	LastIndexingJob []LastIndexingJobParameters `json:"lastIndexingJob,omitempty" tf:"last_indexing_job,omitempty"`

	// Name of the Knowledge Base
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Knowledge Base
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region of the Knowledge Base
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// List of tags
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User ID of the Knowledge Base
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type LastIndexingJobInitParameters struct {

	// Number of completed datasources in the last indexing job
	CompletedDatasources *float64 `json:"completedDatasources,omitempty" tf:"completed_datasources,omitempty"`

	// Datasource UUIDs for the last indexing job
	DataSourceUuids []*string `json:"dataSourceUuids,omitempty" tf:"data_source_uuids,omitempty"`

	// Phase of the last indexing job
	Phase *string `json:"phase,omitempty" tf:"phase,omitempty"`

	// Number of tokens processed in the last indexing job
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`

	// Total number of datasources in the last indexing job
	TotalDatasources *float64 `json:"totalDatasources,omitempty" tf:"total_datasources,omitempty"`

	// ).
	// UUID  of the last indexing job
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type LastIndexingJobObservation struct {

	// Number of completed datasources in the last indexing job
	CompletedDatasources *float64 `json:"completedDatasources,omitempty" tf:"completed_datasources,omitempty"`

	// Created At timestamp for the last indexing job
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Datasource UUIDs for the last indexing job
	DataSourceUuids []*string `json:"dataSourceUuids,omitempty" tf:"data_source_uuids,omitempty"`

	// Timestamp when the last indexing job finished
	FinishedAt *string `json:"finishedAt,omitempty" tf:"finished_at,omitempty"`

	// ).
	// UUID  of the Knowledge Base for the last indexing job
	KnowledgeBaseUUID *string `json:"knowledgeBaseUuid,omitempty" tf:"knowledge_base_uuid,omitempty"`

	// Phase of the last indexing job
	Phase *string `json:"phase,omitempty" tf:"phase,omitempty"`

	// Timestamp when the last indexing job started
	StartedAt *string `json:"startedAt,omitempty" tf:"started_at,omitempty"`

	// Number of tokens processed in the last indexing job
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`

	// Total number of datasources in the last indexing job
	TotalDatasources *float64 `json:"totalDatasources,omitempty" tf:"total_datasources,omitempty"`

	// ).
	// UUID  of the last indexing job
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Timestamp when the last indexing job updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type LastIndexingJobParameters struct {

	// Number of completed datasources in the last indexing job
	// +kubebuilder:validation:Optional
	CompletedDatasources *float64 `json:"completedDatasources,omitempty" tf:"completed_datasources,omitempty"`

	// Datasource UUIDs for the last indexing job
	// +kubebuilder:validation:Optional
	DataSourceUuids []*string `json:"dataSourceUuids,omitempty" tf:"data_source_uuids,omitempty"`

	// Phase of the last indexing job
	// +kubebuilder:validation:Optional
	Phase *string `json:"phase,omitempty" tf:"phase,omitempty"`

	// Number of tokens processed in the last indexing job
	// +kubebuilder:validation:Optional
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`

	// Total number of datasources in the last indexing job
	// +kubebuilder:validation:Optional
	TotalDatasources *float64 `json:"totalDatasources,omitempty" tf:"total_datasources,omitempty"`

	// ).
	// UUID  of the last indexing job
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ModelAgreementInitParameters struct {

	// Description of the agreement
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the agreement
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// URL of the agreement
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// UUID of the agreement
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ModelAgreementObservation struct {

	// Description of the agreement
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the agreement
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// URL of the agreement
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// UUID of the agreement
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ModelAgreementParameters struct {

	// Description of the agreement
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the agreement
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// URL of the agreement
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// UUID of the agreement
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ModelInitParameters struct {

	// Agreement information for the model
	Agreement []AgreementInitParameters `json:"agreement,omitempty" tf:"agreement,omitempty"`

	// Inference name of the model
	InferenceName *string `json:"inferenceName,omitempty" tf:"inference_name,omitempty"`

	// Infernce version of the model
	InferenceVersion *string `json:"inferenceVersion,omitempty" tf:"inference_version,omitempty"`

	// Indicates if the Model Base is foundational
	IsFoundational *bool `json:"isFoundational,omitempty" tf:"is_foundational,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// Parent UUID of the Model
	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// Provider of the Model
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// URL of the Model
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Indicates if the Model upload is complete
	UploadComplete *bool `json:"uploadComplete,omitempty" tf:"upload_complete,omitempty"`

	// List of Usecases for the Model
	Usecases []*string `json:"usecases,omitempty" tf:"usecases,omitempty"`

	// URL of the Model
	Versions []VersionsInitParameters `json:"versions,omitempty" tf:"versions,omitempty"`
}

type ModelObservation struct {

	// Agreement information for the model
	Agreement []AgreementObservation `json:"agreement,omitempty" tf:"agreement,omitempty"`

	// Created At timestamp for the Knowledge Base
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Inference name of the model
	InferenceName *string `json:"inferenceName,omitempty" tf:"inference_name,omitempty"`

	// Infernce version of the model
	InferenceVersion *string `json:"inferenceVersion,omitempty" tf:"inference_version,omitempty"`

	// Indicates if the Model Base is foundational
	IsFoundational *bool `json:"isFoundational,omitempty" tf:"is_foundational,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// Parent UUID of the Model
	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// Provider of the Model
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// URL of the Model
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Timestamp when the Knowledge Base was updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// Indicates if the Model upload is complete
	UploadComplete *bool `json:"uploadComplete,omitempty" tf:"upload_complete,omitempty"`

	// List of Usecases for the Model
	Usecases []*string `json:"usecases,omitempty" tf:"usecases,omitempty"`

	// URL of the Model
	Versions []VersionsObservation `json:"versions,omitempty" tf:"versions,omitempty"`
}

type ModelParameters struct {

	// Agreement information for the model
	// +kubebuilder:validation:Optional
	Agreement []AgreementParameters `json:"agreement,omitempty" tf:"agreement,omitempty"`

	// Inference name of the model
	// +kubebuilder:validation:Optional
	InferenceName *string `json:"inferenceName,omitempty" tf:"inference_name,omitempty"`

	// Infernce version of the model
	// +kubebuilder:validation:Optional
	InferenceVersion *string `json:"inferenceVersion,omitempty" tf:"inference_version,omitempty"`

	// Indicates if the Model Base is foundational
	// +kubebuilder:validation:Optional
	IsFoundational *bool `json:"isFoundational,omitempty" tf:"is_foundational,omitempty"`

	// Name of the Knowledge Base
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// Parent UUID of the Model
	// +kubebuilder:validation:Optional
	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// Provider of the Model
	// +kubebuilder:validation:Optional
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// URL of the Model
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Indicates if the Model upload is complete
	// +kubebuilder:validation:Optional
	UploadComplete *bool `json:"uploadComplete,omitempty" tf:"upload_complete,omitempty"`

	// List of Usecases for the Model
	// +kubebuilder:validation:Optional
	Usecases []*string `json:"usecases,omitempty" tf:"usecases,omitempty"`

	// URL of the Model
	// +kubebuilder:validation:Optional
	Versions []VersionsParameters `json:"versions,omitempty" tf:"versions,omitempty"`
}

type ModelVersionsInitParameters struct {

	// Major version of the model
	Major *float64 `json:"major,omitempty" tf:"major,omitempty"`

	// Minor version of the model
	Minor *float64 `json:"minor,omitempty" tf:"minor,omitempty"`

	// Patch version of the model
	Patch *float64 `json:"patch,omitempty" tf:"patch,omitempty"`
}

type ModelVersionsObservation struct {

	// Major version of the model
	Major *float64 `json:"major,omitempty" tf:"major,omitempty"`

	// Minor version of the model
	Minor *float64 `json:"minor,omitempty" tf:"minor,omitempty"`

	// Patch version of the model
	Patch *float64 `json:"patch,omitempty" tf:"patch,omitempty"`
}

type ModelVersionsParameters struct {

	// Major version of the model
	// +kubebuilder:validation:Optional
	Major *float64 `json:"major,omitempty" tf:"major,omitempty"`

	// Minor version of the model
	// +kubebuilder:validation:Optional
	Minor *float64 `json:"minor,omitempty" tf:"minor,omitempty"`

	// Patch version of the model
	// +kubebuilder:validation:Optional
	Patch *float64 `json:"patch,omitempty" tf:"patch,omitempty"`
}

type OpenAIAPIKeyInitParameters struct {

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type OpenAIAPIKeyObservation struct {

	// Timestamp when the API Key was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Deleted At timestamp for the API Key
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the API Key
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type OpenAIAPIKeyParameters struct {

	// Created By user ID for the API Key
	// +kubebuilder:validation:Optional
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ParentAgentsAPIKeyInfosInitParameters struct {

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Updated At timestamp for the API Key
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ParentAgentsAPIKeyInfosObservation struct {

	// API Key value
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Deleted At timestamp for the API Key
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Updated At timestamp for the API Key
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ParentAgentsAPIKeyInfosParameters struct {

	// Created By user ID for the API Key
	// +kubebuilder:validation:Optional
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Updated At timestamp for the API Key
	// +kubebuilder:validation:Optional
	SecretKey *string `json:"secretKey,omitempty" tf:"secret_key,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ParentAgentsAPIKeysInitParameters struct {

	// API Key value
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`
}

type ParentAgentsAPIKeysObservation struct {

	// API Key value
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`
}

type ParentAgentsAPIKeysParameters struct {

	// API Key value
	// +kubebuilder:validation:Optional
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`
}

type ParentAgentsAnthropicAPIKeyInitParameters struct {

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ParentAgentsAnthropicAPIKeyObservation struct {

	// Timestamp when the API Key was created
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Created By user ID for the API Key
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Deleted At timestamp for the API Key
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the API Key
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type ParentAgentsAnthropicAPIKeyParameters struct {

	// Created By user ID for the API Key
	// +kubebuilder:validation:Optional
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ParentAgentsChatbotIdentifiersInitParameters struct {
}

type ParentAgentsChatbotIdentifiersObservation struct {
	ChatbotID *string `json:"chatbotId,omitempty" tf:"chatbot_id,omitempty"`
}

type ParentAgentsChatbotIdentifiersParameters struct {
}

type ParentAgentsChatbotInitParameters struct {

	// Background color for the chatbot button
	ButtonBackgroundColor *string `json:"buttonBackgroundColor,omitempty" tf:"button_background_color,omitempty"`

	// Logo for the chatbot
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Name of the chatbot
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Primary color for the chatbot
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// Secondary color for the chatbot
	SecondaryColor *string `json:"secondaryColor,omitempty" tf:"secondary_color,omitempty"`

	// Starting message for the chatbot
	StartingMessage *string `json:"startingMessage,omitempty" tf:"starting_message,omitempty"`
}

type ParentAgentsChatbotObservation struct {

	// Background color for the chatbot button
	ButtonBackgroundColor *string `json:"buttonBackgroundColor,omitempty" tf:"button_background_color,omitempty"`

	// Logo for the chatbot
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Name of the chatbot
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Primary color for the chatbot
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// Secondary color for the chatbot
	SecondaryColor *string `json:"secondaryColor,omitempty" tf:"secondary_color,omitempty"`

	// Starting message for the chatbot
	StartingMessage *string `json:"startingMessage,omitempty" tf:"starting_message,omitempty"`
}

type ParentAgentsChatbotParameters struct {

	// Background color for the chatbot button
	// +kubebuilder:validation:Optional
	ButtonBackgroundColor *string `json:"buttonBackgroundColor,omitempty" tf:"button_background_color,omitempty"`

	// Logo for the chatbot
	// +kubebuilder:validation:Optional
	Logo *string `json:"logo,omitempty" tf:"logo,omitempty"`

	// Name of the chatbot
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Primary color for the chatbot
	// +kubebuilder:validation:Optional
	PrimaryColor *string `json:"primaryColor,omitempty" tf:"primary_color,omitempty"`

	// Secondary color for the chatbot
	// +kubebuilder:validation:Optional
	SecondaryColor *string `json:"secondaryColor,omitempty" tf:"secondary_color,omitempty"`

	// Starting message for the chatbot
	// +kubebuilder:validation:Optional
	StartingMessage *string `json:"startingMessage,omitempty" tf:"starting_message,omitempty"`
}

type ParentAgentsDeploymentInitParameters struct {

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Status of the Deployment
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Url of the Deployment
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// argument must be set inside this block. Valid values for visibility are: VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_PLAYGROUND, VISIBILITY_DISABLED, or VISIBILITY_UNKNOWN.
	// Visibility of the Deployment
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type ParentAgentsDeploymentObservation struct {

	// API Key value
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Name of the API Key
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Status of the Deployment
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Url of the Deployment
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the Agent
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// argument must be set inside this block. Valid values for visibility are: VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_PLAYGROUND, VISIBILITY_DISABLED, or VISIBILITY_UNKNOWN.
	// Visibility of the Deployment
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type ParentAgentsDeploymentParameters struct {

	// Name of the API Key
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Status of the Deployment
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Url of the Deployment
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// ).
	// API Key value
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// argument must be set inside this block. Valid values for visibility are: VISIBILITY_PRIVATE, VISIBILITY_PUBLIC, VISIBILITY_PLAYGROUND, VISIBILITY_DISABLED, or VISIBILITY_UNKNOWN.
	// Visibility of the Deployment
	// +kubebuilder:validation:Optional
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type ParentAgentsInitParameters struct {

	// List of API Key Infos
	APIKeyInfos []ParentAgentsAPIKeyInfosInitParameters `json:"apiKeyInfos,omitempty" tf:"api_key_infos,omitempty"`

	// List of API Keys
	APIKeys []ParentAgentsAPIKeysInitParameters `json:"apiKeys,omitempty" tf:"api_keys,omitempty"`

	// Anthropic API Key information
	AnthropicAPIKey []ParentAgentsAnthropicAPIKeyInitParameters `json:"anthropicApiKey,omitempty" tf:"anthropic_api_key,omitempty"`

	// ChatBot configuration
	Chatbot []ParentAgentsChatbotInitParameters `json:"chatbot,omitempty" tf:"chatbot,omitempty"`

	// List of Chatbot Identifiers
	ChatbotIdentifiers []ParentAgentsChatbotIdentifiersInitParameters `json:"chatbotIdentifiers,omitempty" tf:"chatbot_identifiers,omitempty"`

	// List of API Key Infos
	Deployment []ParentAgentsDeploymentInitParameters `json:"deployment,omitempty" tf:"deployment,omitempty"`

	// Description for the Agent
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Instruction for the Agent
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// ).
	// Model UUID of the Agent
	ModelUUID *string `json:"modelUuid,omitempty" tf:"model_uuid,omitempty"`

	// Name of the Agent
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Agent
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region where the Agent is deployed
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ParentAgentsObservation struct {

	// List of API Key Infos
	APIKeyInfos []ParentAgentsAPIKeyInfosObservation `json:"apiKeyInfos,omitempty" tf:"api_key_infos,omitempty"`

	// List of API Keys
	APIKeys []ParentAgentsAPIKeysObservation `json:"apiKeys,omitempty" tf:"api_keys,omitempty"`

	// ID of the child agent
	AgentID *string `json:"agentId,omitempty" tf:"agent_id,omitempty"`

	// Anthropic API Key information
	AnthropicAPIKey []ParentAgentsAnthropicAPIKeyObservation `json:"anthropicApiKey,omitempty" tf:"anthropic_api_key,omitempty"`

	// ChatBot configuration
	Chatbot []ParentAgentsChatbotObservation `json:"chatbot,omitempty" tf:"chatbot,omitempty"`

	// List of Chatbot Identifiers
	ChatbotIdentifiers []ParentAgentsChatbotIdentifiersObservation `json:"chatbotIdentifiers,omitempty" tf:"chatbot_identifiers,omitempty"`

	// List of API Key Infos
	Deployment []ParentAgentsDeploymentObservation `json:"deployment,omitempty" tf:"deployment,omitempty"`

	// Description for the Agent
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Instruction for the Agent
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// ).
	// Model UUID of the Agent
	ModelUUID *string `json:"modelUuid,omitempty" tf:"model_uuid,omitempty"`

	// Name of the Agent
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Agent
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region where the Agent is deployed
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ParentAgentsParameters struct {

	// List of API Key Infos
	// +kubebuilder:validation:Optional
	APIKeyInfos []ParentAgentsAPIKeyInfosParameters `json:"apiKeyInfos,omitempty" tf:"api_key_infos,omitempty"`

	// List of API Keys
	// +kubebuilder:validation:Optional
	APIKeys []ParentAgentsAPIKeysParameters `json:"apiKeys,omitempty" tf:"api_keys,omitempty"`

	// Anthropic API Key information
	// +kubebuilder:validation:Optional
	AnthropicAPIKey []ParentAgentsAnthropicAPIKeyParameters `json:"anthropicApiKey,omitempty" tf:"anthropic_api_key,omitempty"`

	// ChatBot configuration
	// +kubebuilder:validation:Optional
	Chatbot []ParentAgentsChatbotParameters `json:"chatbot,omitempty" tf:"chatbot,omitempty"`

	// List of Chatbot Identifiers
	// +kubebuilder:validation:Optional
	ChatbotIdentifiers []ParentAgentsChatbotIdentifiersParameters `json:"chatbotIdentifiers,omitempty" tf:"chatbot_identifiers,omitempty"`

	// List of API Key Infos
	// +kubebuilder:validation:Optional
	Deployment []ParentAgentsDeploymentParameters `json:"deployment,omitempty" tf:"deployment,omitempty"`

	// Description for the Agent
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Instruction for the Agent
	// +kubebuilder:validation:Optional
	Instruction *string `json:"instruction" tf:"instruction,omitempty"`

	// ).
	// Model UUID of the Agent
	// +kubebuilder:validation:Optional
	ModelUUID *string `json:"modelUuid" tf:"model_uuid,omitempty"`

	// Name of the Agent
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Project ID of the Agent
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId" tf:"project_id,omitempty"`

	// Region where the Agent is deployed
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`
}

type TemplateInitParameters struct {

	// Description of the Agent Template
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Instruction for the Agent
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// K value for the Agent Template
	K *float64 `json:"k,omitempty" tf:"k,omitempty"`

	// List of Knowledge Bases
	KnowledgeBases []TemplateKnowledgeBasesInitParameters `json:"knowledgeBases,omitempty" tf:"knowledge_bases,omitempty"`

	// Maximum tokens allowed
	MaxTokens *float64 `json:"maxTokens,omitempty" tf:"max_tokens,omitempty"`

	// Model of the Agent Template
	Model []TemplateModelInitParameters `json:"model,omitempty" tf:"model,omitempty"`

	// Name of the Agent Template
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Agent temperature setting
	Temperature *float64 `json:"temperature,omitempty" tf:"temperature,omitempty"`

	// Top P sampling parameter
	TopP *float64 `json:"topP,omitempty" tf:"top_p,omitempty"`

	// ).
	// uuid of the Agent Template
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type TemplateKnowledgeBasesInitParameters struct {

	// Database ID of the Knowledge Base
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// ).
	// Embedding model UUID for the Knowledge Base
	EmbeddingModelUUID *string `json:"embeddingModelUuid,omitempty" tf:"embedding_model_uuid,omitempty"`

	// Indicates if the Knowledge Base is public
	IsPublic *bool `json:"isPublic,omitempty" tf:"is_public,omitempty"`

	// Last indexing job for the Knowledge Base
	LastIndexingJob []KnowledgeBasesLastIndexingJobInitParameters `json:"lastIndexingJob,omitempty" tf:"last_indexing_job,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Knowledge Base
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region of the Knowledge Base
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// List of tags
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User ID of the Knowledge Base
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TemplateKnowledgeBasesObservation struct {

	// Timestamp when the Knowledge Base was added to the Agent
	AddedToAgentAt *string `json:"addedToAgentAt,omitempty" tf:"added_to_agent_at,omitempty"`

	// Created At timestamp for the Knowledge Base
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Database ID of the Knowledge Base
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// ).
	// Embedding model UUID for the Knowledge Base
	EmbeddingModelUUID *string `json:"embeddingModelUuid,omitempty" tf:"embedding_model_uuid,omitempty"`

	// Indicates if the Knowledge Base is public
	IsPublic *bool `json:"isPublic,omitempty" tf:"is_public,omitempty"`

	// Last indexing job for the Knowledge Base
	LastIndexingJob []KnowledgeBasesLastIndexingJobObservation `json:"lastIndexingJob,omitempty" tf:"last_indexing_job,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Knowledge Base
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region of the Knowledge Base
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// List of tags
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// ).
	// UUID of the Knowledge Base
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Timestamp when the Knowledge Base was updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// User ID of the Knowledge Base
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TemplateKnowledgeBasesParameters struct {

	// Database ID of the Knowledge Base
	// +kubebuilder:validation:Optional
	DatabaseID *string `json:"databaseId,omitempty" tf:"database_id,omitempty"`

	// ).
	// Embedding model UUID for the Knowledge Base
	// +kubebuilder:validation:Optional
	EmbeddingModelUUID *string `json:"embeddingModelUuid,omitempty" tf:"embedding_model_uuid,omitempty"`

	// Indicates if the Knowledge Base is public
	// +kubebuilder:validation:Optional
	IsPublic *bool `json:"isPublic,omitempty" tf:"is_public,omitempty"`

	// Last indexing job for the Knowledge Base
	// +kubebuilder:validation:Optional
	LastIndexingJob []KnowledgeBasesLastIndexingJobParameters `json:"lastIndexingJob,omitempty" tf:"last_indexing_job,omitempty"`

	// Name of the Knowledge Base
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Project ID of the Knowledge Base
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Region of the Knowledge Base
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// List of tags
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// User ID of the Knowledge Base
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TemplateModelInitParameters struct {

	// Agreement information for the model
	Agreement []ModelAgreementInitParameters `json:"agreement,omitempty" tf:"agreement,omitempty"`

	// Inference name of the model
	InferenceName *string `json:"inferenceName,omitempty" tf:"inference_name,omitempty"`

	// Infernce version of the model
	InferenceVersion *string `json:"inferenceVersion,omitempty" tf:"inference_version,omitempty"`

	// Indicates if the Model Base is foundational
	IsFoundational *bool `json:"isFoundational,omitempty" tf:"is_foundational,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// Parent UUID of the Model
	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// Provider of the Model
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// URL of the Model
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Indicates if the Model upload is complete
	UploadComplete *bool `json:"uploadComplete,omitempty" tf:"upload_complete,omitempty"`

	// List of Usecases for the Model
	Usecases []*string `json:"usecases,omitempty" tf:"usecases,omitempty"`

	// URL of the Model
	Versions []ModelVersionsInitParameters `json:"versions,omitempty" tf:"versions,omitempty"`
}

type TemplateModelObservation struct {

	// Agreement information for the model
	Agreement []ModelAgreementObservation `json:"agreement,omitempty" tf:"agreement,omitempty"`

	// Created At timestamp for the Knowledge Base
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Inference name of the model
	InferenceName *string `json:"inferenceName,omitempty" tf:"inference_name,omitempty"`

	// Infernce version of the model
	InferenceVersion *string `json:"inferenceVersion,omitempty" tf:"inference_version,omitempty"`

	// Indicates if the Model Base is foundational
	IsFoundational *bool `json:"isFoundational,omitempty" tf:"is_foundational,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// Parent UUID of the Model
	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// Provider of the Model
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// URL of the Model
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Timestamp when the Knowledge Base was updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// Indicates if the Model upload is complete
	UploadComplete *bool `json:"uploadComplete,omitempty" tf:"upload_complete,omitempty"`

	// List of Usecases for the Model
	Usecases []*string `json:"usecases,omitempty" tf:"usecases,omitempty"`

	// URL of the Model
	Versions []ModelVersionsObservation `json:"versions,omitempty" tf:"versions,omitempty"`
}

type TemplateModelParameters struct {

	// Agreement information for the model
	// +kubebuilder:validation:Optional
	Agreement []ModelAgreementParameters `json:"agreement,omitempty" tf:"agreement,omitempty"`

	// Inference name of the model
	// +kubebuilder:validation:Optional
	InferenceName *string `json:"inferenceName,omitempty" tf:"inference_name,omitempty"`

	// Infernce version of the model
	// +kubebuilder:validation:Optional
	InferenceVersion *string `json:"inferenceVersion,omitempty" tf:"inference_version,omitempty"`

	// Indicates if the Model Base is foundational
	// +kubebuilder:validation:Optional
	IsFoundational *bool `json:"isFoundational,omitempty" tf:"is_foundational,omitempty"`

	// Name of the Knowledge Base
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ).
	// Parent UUID of the Model
	// +kubebuilder:validation:Optional
	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// Provider of the Model
	// +kubebuilder:validation:Optional
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// URL of the Model
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Indicates if the Model upload is complete
	// +kubebuilder:validation:Optional
	UploadComplete *bool `json:"uploadComplete,omitempty" tf:"upload_complete,omitempty"`

	// List of Usecases for the Model
	// +kubebuilder:validation:Optional
	Usecases []*string `json:"usecases,omitempty" tf:"usecases,omitempty"`

	// URL of the Model
	// +kubebuilder:validation:Optional
	Versions []ModelVersionsParameters `json:"versions,omitempty" tf:"versions,omitempty"`
}

type TemplateObservation struct {

	// Created At timestamp for the Knowledge Base
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Description of the Agent Template
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Instruction for the Agent
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// K value for the Agent Template
	K *float64 `json:"k,omitempty" tf:"k,omitempty"`

	// List of Knowledge Bases
	KnowledgeBases []TemplateKnowledgeBasesObservation `json:"knowledgeBases,omitempty" tf:"knowledge_bases,omitempty"`

	// Maximum tokens allowed
	MaxTokens *float64 `json:"maxTokens,omitempty" tf:"max_tokens,omitempty"`

	// Model of the Agent Template
	Model []TemplateModelObservation `json:"model,omitempty" tf:"model,omitempty"`

	// Name of the Agent Template
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Agent temperature setting
	Temperature *float64 `json:"temperature,omitempty" tf:"temperature,omitempty"`

	// Top P sampling parameter
	TopP *float64 `json:"topP,omitempty" tf:"top_p,omitempty"`

	// ).
	// uuid of the Agent Template
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Updated At timestamp for the Agent Template
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type TemplateParameters struct {

	// Description of the Agent Template
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Instruction for the Agent
	// +kubebuilder:validation:Optional
	Instruction *string `json:"instruction,omitempty" tf:"instruction,omitempty"`

	// K value for the Agent Template
	// +kubebuilder:validation:Optional
	K *float64 `json:"k,omitempty" tf:"k,omitempty"`

	// List of Knowledge Bases
	// +kubebuilder:validation:Optional
	KnowledgeBases []TemplateKnowledgeBasesParameters `json:"knowledgeBases,omitempty" tf:"knowledge_bases,omitempty"`

	// Maximum tokens allowed
	// +kubebuilder:validation:Optional
	MaxTokens *float64 `json:"maxTokens,omitempty" tf:"max_tokens,omitempty"`

	// Model of the Agent Template
	// +kubebuilder:validation:Optional
	Model []TemplateModelParameters `json:"model,omitempty" tf:"model,omitempty"`

	// Name of the Agent Template
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Agent temperature setting
	// +kubebuilder:validation:Optional
	Temperature *float64 `json:"temperature,omitempty" tf:"temperature,omitempty"`

	// Top P sampling parameter
	// +kubebuilder:validation:Optional
	TopP *float64 `json:"topP,omitempty" tf:"top_p,omitempty"`

	// ).
	// uuid of the Agent Template
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type VersionsInitParameters struct {

	// Major version of the model
	Major *float64 `json:"major,omitempty" tf:"major,omitempty"`

	// Minor version of the model
	Minor *float64 `json:"minor,omitempty" tf:"minor,omitempty"`

	// Patch version of the model
	Patch *float64 `json:"patch,omitempty" tf:"patch,omitempty"`
}

type VersionsObservation struct {

	// Major version of the model
	Major *float64 `json:"major,omitempty" tf:"major,omitempty"`

	// Minor version of the model
	Minor *float64 `json:"minor,omitempty" tf:"minor,omitempty"`

	// Patch version of the model
	Patch *float64 `json:"patch,omitempty" tf:"patch,omitempty"`
}

type VersionsParameters struct {

	// Major version of the model
	// +kubebuilder:validation:Optional
	Major *float64 `json:"major,omitempty" tf:"major,omitempty"`

	// Minor version of the model
	// +kubebuilder:validation:Optional
	Minor *float64 `json:"minor,omitempty" tf:"minor,omitempty"`

	// Patch version of the model
	// +kubebuilder:validation:Optional
	Patch *float64 `json:"patch,omitempty" tf:"patch,omitempty"`
}

// AgentSpec defines the desired state of Agent
type AgentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AgentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AgentInitParameters `json:"initProvider,omitempty"`
}

// AgentStatus defines the observed state of Agent.
type AgentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AgentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Agent is the Schema for the Agents API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,do}
type Agent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instruction) || (has(self.initProvider) && has(self.initProvider.instruction))",message="spec.forProvider.instruction is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.modelUuid) || (has(self.initProvider) && has(self.initProvider.modelUuid))",message="spec.forProvider.modelUuid is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   AgentSpec   `json:"spec"`
	Status AgentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AgentList contains a list of Agents
type AgentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Agent `json:"items"`
}

// Repository type metadata.
var (
	Agent_Kind             = "Agent"
	Agent_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Agent_Kind}.String()
	Agent_KindAPIVersion   = Agent_Kind + "." + CRDGroupVersion.String()
	Agent_GroupVersionKind = CRDGroupVersion.WithKind(Agent_Kind)
)

func init() {
	SchemeBuilder.Register(&Agent{}, &AgentList{})
}
