/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/container/v1alpha1"
	v1alpha1custom "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/custom/v1alpha1"
	v1alpha1database "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/database/v1alpha1"
	v1alpha1digitalocean "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/digitalocean/v1alpha1"
	v1alpha1dns "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/dns/v1alpha1"
	v1alpha1droplet "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/droplet/v1alpha1"
	v1alpha1gradientai "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/gradientai/v1alpha1"
	v1alpha1kubernetes "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/kubernetes/v1alpha1"
	v1alpha1monitor "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/monitor/v1alpha1"
	v1alpha1networking "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/networking/v1alpha1"
	v1alpha1nfs "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/nfs/v1alpha1"
	v1alpha1project "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/project/v1alpha1"
	v1alpha1spaces "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/spaces/v1alpha1"
	v1alpha1ssh "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/ssh/v1alpha1"
	v1alpha1uptime "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/uptime/v1alpha1"
	v1alpha1cluster "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/v1alpha1"
	v1beta1 "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/v1beta1"
	v1alpha1volume "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/volume/v1alpha1"
	v1alpha1vpc "github.com/crossplane-contrib/provider-upjet-digitalocean/apis/cluster/vpc/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1custom.SchemeBuilder.AddToScheme,
		v1alpha1database.SchemeBuilder.AddToScheme,
		v1alpha1digitalocean.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1droplet.SchemeBuilder.AddToScheme,
		v1alpha1gradientai.SchemeBuilder.AddToScheme,
		v1alpha1kubernetes.SchemeBuilder.AddToScheme,
		v1alpha1monitor.SchemeBuilder.AddToScheme,
		v1alpha1networking.SchemeBuilder.AddToScheme,
		v1alpha1nfs.SchemeBuilder.AddToScheme,
		v1alpha1project.SchemeBuilder.AddToScheme,
		v1alpha1spaces.SchemeBuilder.AddToScheme,
		v1alpha1ssh.SchemeBuilder.AddToScheme,
		v1alpha1uptime.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1volume.SchemeBuilder.AddToScheme,
		v1alpha1vpc.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
