/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IndexingJobCancelInitParameters struct {

	// The UUID of the indexing job to cancel.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type IndexingJobCancelObservation struct {

	// Number of data sources that were completed before cancellation.
	CompletedDatasources *float64 `json:"completedDatasources,omitempty" tf:"completed_datasources,omitempty"`

	// When the indexing job was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// List of data source UUIDs associated with this indexing job.
	DataSourceUuids []*string `json:"dataSourceUuids,omitempty" tf:"data_source_uuids,omitempty"`

	// When the indexing job was finished.
	FinishedAt *string `json:"finishedAt,omitempty" tf:"finished_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The UUID of the knowledge base associated with this indexing job.
	KnowledgeBaseUUID *string `json:"knowledgeBaseUuid,omitempty" tf:"knowledge_base_uuid,omitempty"`

	// Current phase of the indexing job.
	Phase *string `json:"phase,omitempty" tf:"phase,omitempty"`

	// When the indexing job was started.
	StartedAt *string `json:"startedAt,omitempty" tf:"started_at,omitempty"`

	// The status of the indexing job after cancellation.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Number of tokens processed before cancellation.
	Tokens *float64 `json:"tokens,omitempty" tf:"tokens,omitempty"`

	// Total number of data sources in the indexing job.
	TotalDatasources *float64 `json:"totalDatasources,omitempty" tf:"total_datasources,omitempty"`

	// Total number of items that failed during indexing.
	TotalItemsFailed *float64 `json:"totalItemsFailed,omitempty" tf:"total_items_failed,omitempty"`

	// Total number of items that were successfully indexed.
	TotalItemsIndexed *float64 `json:"totalItemsIndexed,omitempty" tf:"total_items_indexed,omitempty"`

	// Total number of items that were skipped during indexing.
	TotalItemsSkipped *float64 `json:"totalItemsSkipped,omitempty" tf:"total_items_skipped,omitempty"`

	// The UUID of the indexing job to cancel.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// When the indexing job was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type IndexingJobCancelParameters struct {

	// The UUID of the indexing job to cancel.
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

// IndexingJobCancelSpec defines the desired state of IndexingJobCancel
type IndexingJobCancelSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IndexingJobCancelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IndexingJobCancelInitParameters `json:"initProvider,omitempty"`
}

// IndexingJobCancelStatus defines the observed state of IndexingJobCancel.
type IndexingJobCancelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IndexingJobCancelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IndexingJobCancel is the Schema for the IndexingJobCancels API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,do}
type IndexingJobCancel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.uuid) || (has(self.initProvider) && has(self.initProvider.uuid))",message="spec.forProvider.uuid is a required parameter"
	Spec   IndexingJobCancelSpec   `json:"spec"`
	Status IndexingJobCancelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IndexingJobCancelList contains a list of IndexingJobCancels
type IndexingJobCancelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IndexingJobCancel `json:"items"`
}

// Repository type metadata.
var (
	IndexingJobCancel_Kind             = "IndexingJobCancel"
	IndexingJobCancel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IndexingJobCancel_Kind}.String()
	IndexingJobCancel_KindAPIVersion   = IndexingJobCancel_Kind + "." + CRDGroupVersion.String()
	IndexingJobCancel_GroupVersionKind = CRDGroupVersion.WithKind(IndexingJobCancel_Kind)
)

func init() {
	SchemeBuilder.Register(&IndexingJobCancel{}, &IndexingJobCancelList{})
}
