/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type OpenAIAPIKeyInitParameters_2 struct {

	// The OpenAI API key.
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// Models associated with the OpenAI API key
	Model []OpenAIAPIKeyModelInitParameters `json:"model,omitempty" tf:"model,omitempty"`

	// A name for the API key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OpenAIAPIKeyModelAgreementInitParameters struct {

	// Description of the agreement
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the agreement
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// URL of the agreement
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// UUID of the agreement
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type OpenAIAPIKeyModelAgreementObservation struct {

	// Description of the agreement
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the agreement
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// URL of the agreement
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// UUID of the agreement
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type OpenAIAPIKeyModelAgreementParameters struct {

	// Description of the agreement
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the agreement
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// URL of the agreement
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// UUID of the agreement
	// +kubebuilder:validation:Optional
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type OpenAIAPIKeyModelInitParameters struct {

	// Agreement information for the model
	Agreement []OpenAIAPIKeyModelAgreementInitParameters `json:"agreement,omitempty" tf:"agreement,omitempty"`

	// Inference name of the model
	InferenceName *string `json:"inferenceName,omitempty" tf:"inference_name,omitempty"`

	// Infernce version of the model
	InferenceVersion *string `json:"inferenceVersion,omitempty" tf:"inference_version,omitempty"`

	// Indicates if the Model Base is foundational
	IsFoundational *bool `json:"isFoundational,omitempty" tf:"is_foundational,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Parent UUID of the Model
	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// Provider of the Model
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// URL of the Model
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Indicates if the Model upload is complete
	UploadComplete *bool `json:"uploadComplete,omitempty" tf:"upload_complete,omitempty"`

	// List of Usecases for the Model
	Usecases []*string `json:"usecases,omitempty" tf:"usecases,omitempty"`

	// URL of the Model
	Versions []OpenAIAPIKeyModelVersionsInitParameters `json:"versions,omitempty" tf:"versions,omitempty"`
}

type OpenAIAPIKeyModelObservation struct {

	// Agreement information for the model
	Agreement []OpenAIAPIKeyModelAgreementObservation `json:"agreement,omitempty" tf:"agreement,omitempty"`

	// Created At timestamp for the Knowledge Base
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Inference name of the model
	InferenceName *string `json:"inferenceName,omitempty" tf:"inference_name,omitempty"`

	// Infernce version of the model
	InferenceVersion *string `json:"inferenceVersion,omitempty" tf:"inference_version,omitempty"`

	// Indicates if the Model Base is foundational
	IsFoundational *bool `json:"isFoundational,omitempty" tf:"is_foundational,omitempty"`

	// Name of the Knowledge Base
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Parent UUID of the Model
	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// Provider of the Model
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// URL of the Model
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Timestamp when the Knowledge Base was updated
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// Indicates if the Model upload is complete
	UploadComplete *bool `json:"uploadComplete,omitempty" tf:"upload_complete,omitempty"`

	// List of Usecases for the Model
	Usecases []*string `json:"usecases,omitempty" tf:"usecases,omitempty"`

	// URL of the Model
	Versions []OpenAIAPIKeyModelVersionsObservation `json:"versions,omitempty" tf:"versions,omitempty"`
}

type OpenAIAPIKeyModelParameters struct {

	// Agreement information for the model
	// +kubebuilder:validation:Optional
	Agreement []OpenAIAPIKeyModelAgreementParameters `json:"agreement,omitempty" tf:"agreement,omitempty"`

	// Inference name of the model
	// +kubebuilder:validation:Optional
	InferenceName *string `json:"inferenceName,omitempty" tf:"inference_name,omitempty"`

	// Infernce version of the model
	// +kubebuilder:validation:Optional
	InferenceVersion *string `json:"inferenceVersion,omitempty" tf:"inference_version,omitempty"`

	// Indicates if the Model Base is foundational
	// +kubebuilder:validation:Optional
	IsFoundational *bool `json:"isFoundational,omitempty" tf:"is_foundational,omitempty"`

	// Name of the Knowledge Base
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Parent UUID of the Model
	// +kubebuilder:validation:Optional
	ParentUUID *string `json:"parentUuid,omitempty" tf:"parent_uuid,omitempty"`

	// Provider of the Model
	// +kubebuilder:validation:Optional
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// URL of the Model
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Indicates if the Model upload is complete
	// +kubebuilder:validation:Optional
	UploadComplete *bool `json:"uploadComplete,omitempty" tf:"upload_complete,omitempty"`

	// List of Usecases for the Model
	// +kubebuilder:validation:Optional
	Usecases []*string `json:"usecases,omitempty" tf:"usecases,omitempty"`

	// URL of the Model
	// +kubebuilder:validation:Optional
	Versions []OpenAIAPIKeyModelVersionsParameters `json:"versions,omitempty" tf:"versions,omitempty"`
}

type OpenAIAPIKeyModelVersionsInitParameters struct {

	// Major version of the model
	Major *float64 `json:"major,omitempty" tf:"major,omitempty"`

	// Minor version of the model
	Minor *float64 `json:"minor,omitempty" tf:"minor,omitempty"`

	// Patch version of the model
	Patch *float64 `json:"patch,omitempty" tf:"patch,omitempty"`
}

type OpenAIAPIKeyModelVersionsObservation struct {

	// Major version of the model
	Major *float64 `json:"major,omitempty" tf:"major,omitempty"`

	// Minor version of the model
	Minor *float64 `json:"minor,omitempty" tf:"minor,omitempty"`

	// Patch version of the model
	Patch *float64 `json:"patch,omitempty" tf:"patch,omitempty"`
}

type OpenAIAPIKeyModelVersionsParameters struct {

	// Major version of the model
	// +kubebuilder:validation:Optional
	Major *float64 `json:"major,omitempty" tf:"major,omitempty"`

	// Minor version of the model
	// +kubebuilder:validation:Optional
	Minor *float64 `json:"minor,omitempty" tf:"minor,omitempty"`

	// Patch version of the model
	// +kubebuilder:validation:Optional
	Patch *float64 `json:"patch,omitempty" tf:"patch,omitempty"`
}

type OpenAIAPIKeyObservation_2 struct {

	// The OpenAI API key.
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// When the API key was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Who created the API key.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// When the API key was deleted.
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Models associated with the OpenAI API key
	Model []OpenAIAPIKeyModelObservation `json:"model,omitempty" tf:"model,omitempty"`

	// A name for the API key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The UUID of the API key.
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// When the API key was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type OpenAIAPIKeyParameters_2 struct {

	// The OpenAI API key.
	// +kubebuilder:validation:Optional
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// Models associated with the OpenAI API key
	// +kubebuilder:validation:Optional
	Model []OpenAIAPIKeyModelParameters `json:"model,omitempty" tf:"model,omitempty"`

	// A name for the API key.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// OpenAIAPIKeySpec defines the desired state of OpenAIAPIKey
type OpenAIAPIKeySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OpenAIAPIKeyParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OpenAIAPIKeyInitParameters_2 `json:"initProvider,omitempty"`
}

// OpenAIAPIKeyStatus defines the observed state of OpenAIAPIKey.
type OpenAIAPIKeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OpenAIAPIKeyObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OpenAIAPIKey is the Schema for the OpenAIAPIKeys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,do}
type OpenAIAPIKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiKey) || (has(self.initProvider) && has(self.initProvider.apiKey))",message="spec.forProvider.apiKey is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OpenAIAPIKeySpec   `json:"spec"`
	Status OpenAIAPIKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OpenAIAPIKeyList contains a list of OpenAIAPIKeys
type OpenAIAPIKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OpenAIAPIKey `json:"items"`
}

// Repository type metadata.
var (
	OpenAIAPIKey_Kind             = "OpenAIAPIKey"
	OpenAIAPIKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OpenAIAPIKey_Kind}.String()
	OpenAIAPIKey_KindAPIVersion   = OpenAIAPIKey_Kind + "." + CRDGroupVersion.String()
	OpenAIAPIKey_GroupVersionKind = CRDGroupVersion.WithKind(OpenAIAPIKey_Kind)
)

func init() {
	SchemeBuilder.Register(&OpenAIAPIKey{}, &OpenAIAPIKeyList{})
}
