apiVersion: compute.digitalocean.crossplane.io/v1alpha1
kind: Droplet
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/droplet
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    image: ubuntu-20-04-x64
    name: web-1
    region: nyc2
    size: s-1vcpu-1gb
