apiVersion: database.digitalocean.crossplane.io/v1alpha1
kind: PostgreSQLConfig
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/postgresqlconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    timezone: UTC
    workMem: 16

---

apiVersion: database.digitalocean.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/postgresqlconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    engine: pg
    name: example-postgresql-cluster
    nodeCount: 1
    region: nyc1
    size: db-s-1vcpu-1gb
    version: "15"
