/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RegistriesInitParameters struct {
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	SubscriptionTierSlug *string `json:"subscriptionTierSlug,omitempty" tf:"subscription_tier_slug,omitempty"`
}

type RegistriesObservation struct {
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	ServerURL *string `json:"serverUrl,omitempty" tf:"server_url,omitempty"`

	StorageUsageBytes *float64 `json:"storageUsageBytes,omitempty" tf:"storage_usage_bytes,omitempty"`

	SubscriptionTierSlug *string `json:"subscriptionTierSlug,omitempty" tf:"subscription_tier_slug,omitempty"`
}

type RegistriesParameters struct {

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// +kubebuilder:validation:Optional
	SubscriptionTierSlug *string `json:"subscriptionTierSlug,omitempty" tf:"subscription_tier_slug,omitempty"`
}

// RegistriesSpec defines the desired state of Registries
type RegistriesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RegistriesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RegistriesInitParameters `json:"initProvider,omitempty"`
}

// RegistriesStatus defines the observed state of Registries.
type RegistriesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RegistriesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Registries is the Schema for the Registriess API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,do}
type Registries struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subscriptionTierSlug) || (has(self.initProvider) && has(self.initProvider.subscriptionTierSlug))",message="spec.forProvider.subscriptionTierSlug is a required parameter"
	Spec   RegistriesSpec   `json:"spec"`
	Status RegistriesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RegistriesList contains a list of Registriess
type RegistriesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Registries `json:"items"`
}

// Repository type metadata.
var (
	Registries_Kind             = "Registries"
	Registries_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Registries_Kind}.String()
	Registries_KindAPIVersion   = Registries_Kind + "." + CRDGroupVersion.String()
	Registries_GroupVersionKind = CRDGroupVersion.WithKind(Registries_Kind)
)

func init() {
	SchemeBuilder.Register(&Registries{}, &RegistriesList{})
}
